### ISSUE TITLE
Wrong result of MAX and MIN

### ISSUE THREAD

**Issue by exialin** [heterodb/pg-strom#362]
Hello. I found the result of MAX and MIN might be wrong when testing GpuPreAgg.

My table is created as:
```
create table j1 (c1 smallint, c2 smallint);
insert into j1 select generate_series(1,10000), random()*32767/10;
```

1. MAX

MAX query on original j1 is correct. But if some rows are changed to `NULL`, the result might be wrong, like:
```
testdb=# update j1 set c2 = NULL where c2 % 5 = 0;
testdb=# select max(c2) from j1;
  max
--------
 -32768
(1 row)
```

It seems that smallint overflowed. However, I cannot reproduce the same error with `c1` and `c2` both being `integer`.

2. MIN

The result of MIN is always 0, like:
```
testdb=# select min(c1) from j1;
 min
-----
   0
(1 row)
```

Test environment is PostgreSQL 9.6.8 and latest PG-Strom 2.0.

Regards

**Comment by kaigai** [comment]
GpuPreAgg internally deals with `smallint` as `int` (32bit) because of atomic operation specification. It may affect to the wrong results. Let me check the problem.

**Comment by kaigai** [comment]
120285b04f73539fbabef40462839a2eb1eef290 should fix the problem.
Please drop the extension of pg-strom once, then create pg-strom extension to refresh self-defined alternative aggregate function.
```
DROP EXTENSION pg_strom;
CREATE EXTENSION pg_strom;
```
The minimum value of int16 is -32768 (0x00008000), however, it is larger than any other positive
16bit integers (0...32768) when arithmetic logic handled the value as 32bit.
Because of atomic operation specification in GPU kernel, min/max(smallint) was implemented
using 32bit operator, so NULL-value which is initialized to the minimum value overwrites any other
valid value once it gets merged to non-NULL values.

Thanks for your reports.

**Comment by exialin** [comment]
Great! MAX is correct now. But the MIN problem is still there...

**Comment by kaigai** [comment]
Sorry, 0f90503d2b6ff4238fe037431eeacdc0938bc3c7 fixed the problem.

Min() operation without GROUP BY is processed by gpupreagg_nogroup_reduction().
It stores the reduction results to the final buffer, however, it is initialized to zero.
If X is positive, Min(X, 0) is 0, then Min() reported 0 regardless of the input if no negative numbers.

Thanks,

**Comment by exialin** [comment]
Thanks for the fix.
