### ISSUE TITLE
issue in CUDA_ERROR_INVALID_HANDLE

### ISSUE THREAD

**Issue by maliabd-al-majid** [heterodb/pg-strom#489]
i am using ubuntu 20.04
i  already added CUDA_ENABLE_COREDUMP_ON_EXCEPTION=1 to system environment , but i still getting issue :

`psycopg2.errors.InternalError_: failed on gpuIpcOpenMemHandle: CUDA_ERROR_INVALID_HANDLE - invalid resource handle
`
postgresql log file :

```
2020-12-14 02:29:04.721 CET [64855] logicsem@logicsem ERROR:  failed on gpuIpcOpenMemHandle: CUDA_ERROR_INVALID_HANDLE - invalid resource handle
2020-12-14 02:29:04.721 CET [64855] logicsem@logicsem STATEMENT:  CREATE TABLE "p5_td_node_109_m" AS (SELECT t122.v20,t123.v58,t125.v112,t122.v117,t145.v121, t123.model_count * t122.model_count * t124.model_count * t145.model_count * t125.model_count AS model_count FROM "p5_td_node_123" t123,"p5_td_node_145" t145,"p5_td_node_125" t125,"p5_td_node_122" t122,"p5_td_node_124" t124 WHERE t122.v20 = t123.v20 AND t123.v20 = t124.v20 AND t124.v20 = t125.v20 AND t125.v20 = t145.v20 AND t123.v58 = t124.v58 AND t124.v58 = t145.v58 AND t125.v112 = t145.v112 AND t122.v117 = t145.v117 )
```
i just want to know what causes this issue , and if there is a way to solve it ?

thanks in advance.

**Comment by kaigai** [comment]
Could you ensure `make clean && make install` again?

This CUDA API is used on GpuJoin, to share the inner buffer by multiple backend-workers.

**Comment by maliabd-al-majid** [comment]
i did them , and i still have the same issue .
first i can explain why this issue happen :
i am using 140 views , so in case that i had view which uses large scale query i got issue out_of_memory:
```
    cur.execute(q, p)
psycopg2.OperationalError: SSL SYSCALL error: EOF detected

```
log file : 
```
2020-12-16 23:16:56.613 CET [994] DETAIL:  Failed process was running: INSERT INTO "p1_td_node_50" SELECT * from "p1_td_node_50_v"
2020-12-16 23:16:56.613 CET [994] LOG:  terminating any other active server processes
2020-12-16 23:16:56.613 CET [5975] logicsem@logicsem WARNING:  terminating connection because of crash of another server process
2020-12-16 23:16:56.613 CET [5975] logicsem@logicsem DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
```

so i thought that it is better just to use materalized views to avoid this issue :
so i got issue :

`psycopg2.errors.InternalError_: failed on gpuIpcOpenMemHandle: CUDA_ERROR_INVALID_HANDLE - invalid resource handle
`
log file :

```
2020-12-16 23:19:59.951 CET [6322] logicsem@logicsem ERROR:  failed on gpuIpcOpenMemHandle: CUDA_ERROR_INVALID_HANDLE - invalid resource handle
2020-12-16 23:19:59.951 CET [6322] logicsem@logicsem STATEMENT:  CREATE  materialized view  "p1_td_node_17_v" AS SELECT null::BOOLEAN v4,v12,v50,v67,v68,v74,v79,v111,v126, sum(model_count) AS model_count FROM (SELECT t30.v4,t30.v12,t32.v50,t32.v67,t32.v68,t32.v74,t32.v79,t31.v111,t30.v126, t32.model_count * t30.model_count * t31.model_count AS model_count FROM "p1_td_node_30" t30,"p1_td_node_31" t31,"p1_td_node_32" t32 WHERE t30.v4 = t31.v4 AND t31.v4 = t32.v4 AND t30.v12 = t31.v12 AND t31.v111 = t32.v111 AND t30.v126 = t32.v126 ) AS candidate WHERE (NOT v68 OR NOT v74) GROUP BY v12,v50,v67,v68,v74,v79,v111,v126
```

**Comment by kaigai** [comment]
Can you provide us the relevant table dump (`p1_td_node_30`, `p1_td_node_31`, and `p1_td_node_32`)?
I have no idea to the scenario of the problem reproduction right now, so I like to try reproduce our own environment.

**Comment by maliabd-al-majid** [comment]
it contains 5 tables for two examples :
first query: p1_td_node_107_v
```
 SELECT candidate.v60,
    candidate.v74,
    candidate.v79,
    candidate.v105,
    NULL::boolean AS v130,
    sum(candidate.model_count) AS model_count
   FROM ( WITH introduce AS (
                 SELECT true AS val
                UNION ALL
                 SELECT false AS bool
                )
         SELECT i60.val AS v60,
            i74.val AS v74,
            t121.v79,
            t120.v105,
            t120.v130,
            ((t120.model_count * (1)::numeric) * t121.model_count) AS model_count
           FROM introduce i60,
            p1_td_node_120 t120,
            p1_td_node_121 t121,
            introduce i74
          WHERE (t120.v130 = t121.v130)) candidate
  WHERE ((candidate.v130 OR (NOT candidate.v74)) AND ((NOT candidate.v60) OR (NOT candidate.v74)) AND (candidate.v130 OR (NOT candidate.v60)))
  GROUP BY candidate.v60, candidate.v74, candidate.v79, candidate.v105;
```
second query: p1_td_node_17_v

```
 SELECT NULL::boolean AS v4,
    candidate.v12,
    candidate.v50,
    candidate.v67,
    candidate.v68,
    candidate.v74,
    candidate.v79,
    candidate.v111,
    candidate.v126,
    sum(candidate.model_count) AS model_count
   FROM ( SELECT t30.v4,
            t30.v12,
            t32.v50,
            t32.v67,
            t32.v68,
            t32.v74,
            t32.v79,
            t31.v111,
            t30.v126,
            ((t31.model_count * t30.model_count) * t32.model_count) AS model_count
           FROM p1_td_node_32 t32,
            p1_td_node_30 t30,
            p1_td_node_31 t31
          WHERE ((t30.v4 = t31.v4) AND (t31.v4 = t32.v4) AND (t30.v12 = t31.v12) AND (t31.v111 = t32.v111) AND (t30.v126 = t32.v126))) candidate
  WHERE ((NOT candidate.v68) OR (NOT candidate.v74))
  GROUP BY candidate.v12, candidate.v50, candidate.v67, candidate.v68, candidate.v74, candidate.v79, candidate.v111, candidate.v126;
```
both examples produce the same issue . 

[tables.zip](https://github.com/heterodb/pg-strom/files/5706986/tables.zip)

**Comment by maliabd-al-majid** [comment]
thanks for your effort  , please let me know ,if there is anything else i can provide from my side .

**Comment by maliabd-al-majid** [comment]
sorry for inconvenience , i would to ask if there is any feedback regarding to this issue . 
thanks in advance .

**Comment by kaigai** [comment]
I cannot touch this problem by end of this week, due to the deadline of another task (by commercial contract).
Please undestand our business circumstances.

**Comment by maliabd-al-majid** [comment]
thanks for your response , no problem i can wait .

**Comment by kaigai** [comment]
I could not reproduced the problem you reported, however, I cound meet a different symptom.
It was caused by a data copy with wrong length at GpuNestLoop; that is less frequently used.
And it is fixed at 0d0874e365efeced652aba7ad56f566c15be29da .

This commit fixes the server crash, but not for the problem of gpuIpcOpenMemHandle.
Can you check whether it is reproducible on the latest software?

**Comment by maliabd-al-majid** [comment]
i think issue still exists which causes server crash . 

```
2020-12-28 15:38:41.819 CET [8931] logicsem@logicsem ERROR:  failed on gpuIpcOpenMemHandle: CUDA_ERROR_INVALID_HANDLE - invalid resource handle
2020-12-28 15:38:41.819 CET [8931] logicsem@logicsem STATEMENT:  INSERT INTO "p1_td_node_107" SELECT * from "p1_td_node_107_v"
2020-12-28 15:38:41.840 CET [8928] logicsem@logicsem FATAL:  terminating connection due to administrator command
2020-12-28 15:38:41.840 CET [8931] logicsem@logicsem FATAL:  terminating connection due to administrator command
```
 but now i always get cuda error invalid handle , the good thing that i tried to run it in pgadmin4 , and it is working fine . 
 is there anything that i have to look for ? and change it ? or is there any considerations that i have to follow when i use pg_strom?
![Screenshot from 2020-12-28 15-31-09](https://user-images.githubusercontent.com/16827753/103223242-167fef00-4926-11eb-8715-95d2ce3800f2.png)

**Comment by maliabd-al-majid** [comment]
i have also installed CentOS 8 , to test whether it happens from ubuntu .
the issue that i got:

```
psycopg2.errors.InternalError_: failed on cuLinkAddData: CUDA_ERROR_UNSUPPORTED_PTX_VERSION - the provided PTX was compiled with an unsupported toolchain.
DETAIL:  GPU kernel location: cuda_program.c:526 [link_cuda_libraries]
```
one thing , if i tried it one small number of tables , it works , but issue occurs only  in big number of tables  .

**Comment by kaigai** [comment]
Which version of CUDA Toolkit are you using?
And, which is your GPU model?

This error comes from binary version mismatch between GPU device and GPU binary built for.
Please always ensure `make clean && make -j NCPUS` after `git pull`.

**Comment by kaigai** [comment]
3cf42b8cdbf314c2eefc6516660f980bc9426dd4
Does this commit work for you?

I like to suggest you to upgrade the CUDA Toolkit 11.1, NVIDIA driver 460.27.xx, then rebuild PG-Strom again.

**Comment by maliabd-al-majid** [comment]
i tried it .
now i would say it is a very good step .
sometimes it works , and sometimes i got issue:

`
psycopg2.errors.InternalError_: failed on gpuIpcOpenMemHandle: CUDA_ERROR_INVALID_HANDLE - invalid resource handle
`

**Comment by maliabd-al-majid** [comment]
full error message:
`Traceback (most recent call last):
  File "/home/mohamednadeem/project/dp_on_dbs/dpdb/problem.py", line 376, in node_worker
    self.solve_node(node,db)
  File "/home/mohamednadeem/project/dp_on_dbs/dpdb/problem.py", line 403, in solve_node
    db.insert_select(f"td_node_{node.id}", db.replace_dynamic_tabs(select))
  File "/home/mohamednadeem/project/dp_on_dbs/dpdb/db.py", line 153, in insert_select
    self.execute(q)
  File "/home/mohamednadeem/project/dp_on_dbs/dpdb/db.py", line 75, in execute
    cur.execute(q,p)
psycopg2.errors.InternalError_: failed on gpuIpcOpenMemHandle: CUDA_ERROR_INVALID_HANDLE - invalid resource handle

[WARNING] dpdb: Terminating because of error in worker thread
Traceback (most recent call last):
  File "dpdb.py", line 153, in <module>
    solve_problem(cfg,**vars(args))
  File "dpdb.py", line 88, in solve_problem
    problem.solve()
  File "/home/mohamednadeem/project/dp_on_dbs/dpdb/problem.py", line 346, in solve
    workers[n.id] = e
  File "/home/mohamednadeem/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 636, in __exit__
    self.shutdown(wait=True)
  File "/home/mohamednadeem/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 236, in shutdown
    t.join()
  File "/home/mohamednadeem/anaconda3/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/home/mohamednadeem/anaconda3/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "dpdb.py", line 51, in signal_handler
    admin_db.killall(app_name)
  File "/home/mohamednadeem/project/dp_on_dbs/dpdb/db.py", line 212, in killall
    self.execute(sql.SQL(q),[self._db_name,app_name])
  File "/home/mohamednadeem/project/dp_on_dbs/dpdb/db.py", line 75, in execute
    cur.execute(q,p)
`

**Comment by kaigai** [comment]
Could you run the same query from `psql` client, not a Python script?

I still could not reproduce the problem that you reported.

**Comment by maliabd-al-majid** [comment]
if i run single query on psql client now it works fine , but the thing is that in python i am using commit and rollback transactions . 
so at some point one of queries that works fine on its own , produce that issue , so i want to ask if there is some limits on commit and rollback . 

example of queries  : 
`insert into p1_td_node_9 select * from p1_td_node_9_v`

**Comment by kaigai** [comment]
It should work even if transaction commit/rollback was used.

However, `insert into p1_td_node_9 select * from p1_td_node_9_v` should not produce `failed on gpuIpcOpenMemHandle: CUDA_ERROR_INVALID_HANDLE - invalid resource handle` error, because only GpuJoin uses `gpuIpcOpenMemHandle()`.

What is the problem? How to reproduce it? I'm uncertain about the point you mention about.

**Comment by maliabd-al-majid** [comment]
log file :

`2021-01-03 13:43:17.786 EST [7917] ERROR:  failed on gpuIpcOpenMemHandle: CUDA_ERROR_INVALID_HANDLE - invalid resource handle
2021-01-03 13:43:17.786 EST [7917] STATEMENT:  INSERT INTO "p1_td_node_9" SELECT * from "p1_td_node_9_v"
`
for view p1_td_node_9_v :

` v78 | v79 | v153 | model_count 
-----+-----+------+-------------
 f   | f   |      |         274
 f   | t   |      |         146
 t   | f   |      |         146
`

**Comment by maliabd-al-majid** [comment]
sorry for inconvenience. 

some times i got this issue:
'2021-01-05 18:25:00.650 CET [954] LOG:  background worker "PG-Strom Program Builder-1" (PID 24730) exited with exit code 1
2021-01-05 18:25:00.849 CET [24731] ERROR:  out of CUDA program cache
2021-01-05 18:25:00.851 CET [954] LOG:  background worker "PG-Strom Program Builder-0" (PID 24731) exited with exit code 1
2021-01-05 18:25:01.653 CET [24733] LOG:  CUDA Program Builder-1 with NVRTC version 10.1
2021-01-05 18:25:01.852 CET [24736] LOG:  CUDA Program Builder-0 with NVRTC version 10.1
2021-01-05 18:25:01.941 CET [24733] ERROR:  out of CUDA program cache
2021-01-05 18:25:01.943 CET [954] LOG:  background worker "PG-Strom Program Builder-1" (PID 24733) exited with exit code 1
2021-01-05 18:25:02.118 CET [24736] ERROR:  out of CUDA program cache'


the full log file which might help you :

`2021-01-05 18:25:39.201 CET [1073] LOG:  starting PostgreSQL 12.5 (Ubuntu 12.5-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
2021-01-05 18:25:39.201 CET [1073] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-01-05 18:25:39.204 CET [1073] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-01-05 18:25:39.320 CET [1185] LOG:  database system was shut down at 2021-01-05 18:25:17 CET
2021-01-05 18:25:39.320 CET [1187] LOG:  CUDA Program Builder-1 with NVRTC version 10.1
2021-01-05 18:25:39.320 CET [1188] LOG:  CUDA Program Builder-0 with NVRTC version 10.1
2021-01-05 18:25:39.330 CET [1073] LOG:  database system is ready to accept connections
2021-01-05 18:25:39.341 CET [1073] LOG:  background worker "Gstore_Fdw Starup Kicker" (PID 1199) exited with exit code 1
2021-01-05 18:25:40.350 CET [1073] LOG:  background worker "Gstore_Fdw Starup Kicker" (PID 1358) exited with exit code 1
2021-01-05 18:25:41.361 CET [1073] LOG:  background worker "Gstore_Fdw Starup Kicker" (PID 1574) exited with exit code 1
2021-01-05 18:26:19.413 CET [3629] FATAL:  terminating autovacuum process due to administrator command
2021-01-05 18:27:21.322 CET [4581] logicsem@logicsem ERROR:  failed on gpuIpcOpenMemHandle: CUDA_ERROR_INVALID_HANDLE - invalid resource handle
2021-01-05 18:27:21.322 CET [4581] logicsem@logicsem STATEMENT:  INSERT INTO "p1_td_node_1" SELECT * from "p1_td_node_1_v"
2021-01-05 18:27:21.345 CET [4581] logicsem@logicsem FATAL:  terminating connection due to administrator command
2021-01-05 18:27:21.345 CET [4286] logicsem@logicsem FATAL:  terminating connection due to administrator command
2021-01-05 18:28:59.043 CET [6193] logicsem@logicsem ERROR:  failed on gpuIpcOpenMemHandle: CUDA_ERROR_INVALID_HANDLE - invalid resource handle
2021-01-05 18:28:59.043 CET [6193] logicsem@logicsem STATEMENT:  INSERT INTO "p1_td_node_17" SELECT * from "p1_td_node_17_v"
2021-01-05 18:28:59.066 CET [5797] logicsem@logicsem FATAL:  terminating connection due to administrator command
2021-01-05 18:28:59.066 CET [5978] logicsem@logicsem FATAL:  terminating connection due to administrator command
2021-01-05 18:28:59.066 CET [5978] logicsem@logicsem STATEMENT:  INSERT INTO "p1_td_node_143" SELECT * from "p1_td_node_143_v"
2021-01-05 18:28:59.066 CET [6085] logicsem@logicsem FATAL:  terminating connection due to administrator command
2021-01-05 18:28:59.066 CET [6085] logicsem@logicsem STATEMENT:  INSERT INTO "p1_td_node_29" SELECT * from "p1_td_node_29_v"
2021-01-05 18:28:59.067 CET [6193] logicsem@logicsem FATAL:  terminating connection due to administrator command`

**Comment by maliabd-al-majid** [comment]
screenshot from psql client 
![Screenshot from 2021-01-05 19-01-44](https://user-images.githubusercontent.com/16827753/103682098-b114a980-4f88-11eb-84c6-4ac5c7c21881.png)

`2021-01-05 19:01:36.935 CET [10731] postgres@logicsem ERROR:  failed on gpuIpcOpenMemHandle: CUDA_ERROR_INVALID_HANDLE - invalid resource handle
2021-01-05 19:01:36.935 CET [10731] postgres@logicsem STATEMENT:  INSERT INTO "p1_td_node_1" SELECT * from "p1_td_node_1_v"`

**Comment by maliabd-al-majid** [comment]
please find tables below:

[issue.zip](https://github.com/heterodb/pg-strom/files/5775058/issue.zip)

and just run query:

-note : in first time it will run successfully but when you try to run it for second or third time you will get this issue .

` INSERT INTO "p1_td_node_1" SELECT * from "p1_td_node_1_v"`

![Screenshot from 2021-01-06 10-53-18](https://user-images.githubusercontent.com/16827753/103755059-80c31e80-500d-11eb-963b-d8c6ec9d71f5.png)
![Screenshot from 2021-01-06 10-53-24](https://user-images.githubusercontent.com/16827753/103755060-815bb500-500d-11eb-8ab1-b9f793e27aae.png)

**Comment by maliabd-al-majid** [comment]
please let me know if there is something else i should provide from my side.

thanks for your effort.

**Comment by maliabd-al-majid** [comment]
i would like to ask whether there is any update regarding this issue .

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
